---
# install JDK 1.8
- hosts: localhost
  gather_facts: no

  tasks:
#  - name: downloading jdk
#    get_url:
#      url: "https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jdk-8u202-linux-x64.rpm"
#      headers: 'Cookie:oraclelicense=accept-securebackup-cookie'
#      dest: "/tmp"
      #register: downloaded_file
      #debug: msg="{{downloaded_file}}"
#  - name: install from /tmp
#    yum:
#      #pkg: "jdk-8u202-linux-x64.rpm"
#      name: /tmp/jdk-8u202-linux-x64.rpm
#      state: "installed"
  - name: remove java package in /tmp
    file:
       path: /tmp/jdk-8u202-linux-x64.rpm
       state: absent

